Feature/oe 148 new customer field changes
one-energy/mpwr pull request #12
Opened 2021-03-03 17:23 UTC by Ron-Junior

## Goal

As a user, I want some fields to be auto-populated when I go to insert a new customer and make them easier to search through

## Changeset

Acceptance Criteria

- When user goes to insert a new customer, the sales rep dropdown should automatically get populated with that user’s name (weather the user has the role of a sales rep or not) IF the user has an office

- Sales rep dropdown should be a list of people under you (and include yourself IF the user has an office). If I’m just a sales rep, the dropdown will only have myself in it. If I’m an office manager, it will have everyone in my office but it will get pre-populated with my name

- Make so the first option in “setter” is “Self Gen” and have it be the default when any user goes to add a customer

- When “setter” = “Self Gen”, clear the setter commission field and disable it

- Setter should have a list of everyone in the department

- List options in setter and sales rep in alphabetical order (except for the very first option in setter)

- Make both sales rep and setter fields searchable and always show up to 5 results for search

## Tests

- [ ] Go to one energy
- [ ] On dashboard click on add customer
- [ ] Verify if all changes its all right
- [ ] go to dashboard click on created customer
- [ ] verify if its all right

## Discussion

## Review

For the submitter, initial self-review:

- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency between the changeset and the goal stated above
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Complexity - is the proposed change introducing any unjustified complexity? 
- [ ] Thoroughness of added tests and any missing edge cases

2021-03-04 22:44 UTC, iammayron requested changes

2021-03-04 22:44 UTC, iammayron commented on app/Models/User.php
> +            return User::whereHas('office')->get()->sortBy('first_name');
You could orderBy on eloquent side before the get() function.

2021-03-04 22:44 UTC, iammayron commented on app/Models/User.php
> +                ->orWhere('role', 'Setter')->get()->sortBy('first_name');
You could orderBy on eloquent side before the get() function.

2021-03-04 22:44 UTC, iammayron commented on app/Http/Livewire/Customer/Edit.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
I think that you don't need that toArray() function after get().

2021-03-04 22:44 UTC, iammayron commented on app/Http/Livewire/Customer/Create.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
I think that you don't need that toArray() function after get().

2021-03-04 22:44 UTC, iammayron commented on app/Models/User.php
> +        return $users->sortBy('first_name');
Relation methods must not have logic that doesn't correspond to the relationship, I think that this reduce function and sortBy function are something particular to a single logic.

2021-03-05 13:09 UTC, Ron-Junior commented on app/Http/Livewire/Customer/Edit.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
For some reason, the livewire can not list the collection, and because of this we need toArray

2021-03-05 13:09 UTC, Ron-Junior commented on app/Models/User.php
> +                ->orWhere('role', 'Setter')->get()->sortBy('first_name');
For some reason, the livewire can not list the collection, and because of this we need toArray

2021-03-05 13:22 UTC, Ron-Junior commented on app/Http/Livewire/Customer/Create.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
For some reason, the livewire can not list the collection, and because of this we need toArray

2021-03-05 16:24 UTC, iammayron commented on app/Http/Livewire/Customer/Edit.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
![image](https://user-images.githubusercontent.com/7702807/110143412-00732c80-7db6-11eb-9773-6682cfa28e19.png)

The problem is that you declared the property as an array.

2021-03-05 16:24 UTC, iammayron commented on app/Http/Livewire/Customer/Create.php
> +        $this->setters = User::whereDepartmentId($this->departmentId)->orderBy('first_name')->get()->toArray();
![image](https://user-images.githubusercontent.com/7702807/110143412-00732c80-7db6-11eb-9773-6682cfa28e19.png)

The problem is that you declared the property as an array.

2021-03-05 17:06 UTC, iammayron approved these changes

2021-03-08 16:41 UTC, merged