Feature/oe 183 increase max w throughout system
one-energy/mpwr pull request #48
Opened 2021-03-22 18:31 UTC by Ron-Junior

## Goal

Resize all pages to occupy all size of the screen

## Changeset

## Tests

## Discussion

## Review

For the submitter, initial self-review:

- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency between the changeset and the goal stated above
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Complexity - is the proposed change introducing any unjustified complexity? 
- [ ] Thoroughness of added tests and any missing edge cases

2021-03-23 02:05 UTC, iammayron requested changes

2021-03-23 21:32 UTC, iammayron requested changes

2021-03-23 21:32 UTC, iammayron commented on resources/views/castle/departments/create.blade.php
>              <x-form :route="route('castle.departments.store')" post>
You don't need this `post` attribute, this is already the default type.

2021-03-26 16:23 UTC, lucas-devsq requested changes
Add 8xl for width in tailwind configurations

2021-03-26 17:28 UTC, lucas-devsq approved these changes

2021-03-26 17:28 UTC, merged