feature/OE-234-multiple-managers-team
one-energy/mpwr pull request #89
Opened 2021-04-30 17:57 UTC by devsquad-mathews-lima

## Goal

## Changeset

## Tests

## Discussion

## Review

For the submitter, initial self-review:

- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency between the changeset and the goal stated above
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Complexity - is the proposed change introducing any unjustified complexity? 
- [ ] Thoroughness of added tests and any missing edge cases

2021-05-03 19:46 UTC, Ron-Junior requested changes

2021-05-03 19:46 UTC, Ron-Junior commented on resources/views/livewire/castle/regions.blade.php
> +                                                            </div>
i'm thinking... this code is repeating on regions office and department blade pages. maybe you could create a component to this. 
OBS: just a suggestion.

2021-05-04 14:03 UTC, devsquad-mathews-lima commented on app/Http/Controllers/Castle/RegionController.php
Done

2021-05-04 14:03 UTC, devsquad-mathews-lima commented on app/Http/Controllers/Castle/OfficeController.php
> +        });
Done

2021-05-05 18:27 UTC, Ron-Junior approved these changes

2021-06-21 16:06 UTC, merged