Feature/oe 258 enium points
one-energy/mpwr pull request #97
Opened 2021-05-10 18:16 UTC by ron-junior-devsquad

## Goal

## Changeset

## Tests

## Discussion

## Review

For the submitter, initial self-review:

- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency between the changeset and the goal stated above
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Complexity - is the proposed change introducing any unjustified complexity? 
- [ ] Thoroughness of added tests and any missing edge cases

2021-05-10 20:25 UTC, devsquad-mathews-lima requested changes

2021-05-11 15:40 UTC, ron-junior-devsquad commented on app/Http/Controllers/UserCustomersEniumPointsController.php
> +class UserCustomersEniumPointsController extends Controller
Nop. i'll remove.

2021-05-12 19:06 UTC, devsquad-mathews-lima commented on app/Http/Livewire/Customer/Edit.php
> +            }
I think you could inline instead of nested if statements. Maybe something like:
```
if (cond_01 && cond_2 && cond_3) // sample 01

if ($this->isTrue()) // sample 02
```

2021-05-12 19:08 UTC, devsquad-mathews-lima approved these changes

2021-05-17 23:14 UTC, merged